name: Docker Build and Deploy # workflow

on: # events
  push:
    branches:
      - master

jobs: # jobs
  deploy:
    runs-on: ubuntu-latest

    steps: # steps
      - name: Checkout code # actions
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Build project (NestJS/Next.js ë“±)
        run: yarn build

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project to server
        run: |
          rsync -avz --exclude='.env' -e "ssh -o StrictHostKeyChecking=no" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/LOLFIGHT

      - name: Run docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/LOLFIGHT
            docker-compose down
            docker-compose up -d --build
            docker system prune -a --volumes -f
          EOF
